ORDER_STATUS_CONFIRM = 1
ORDER_STATUS_CANCEL = 2
ORDER_STATUS_RETURN = 3

PAYMENT_STATUS_UNPAYED = 1
PAYMENT_STATUS_PAYED = 2
PAYMENT_STATUS_REFUND = 3

PAYMENT_TYPE_WECHAT = 1
PAYMENT_TYPE_ALIPAY = 2
PAYMENT_TYPE_FREE = 3

SERVICE_PACKAGE_TYPE_FREE = 1
SERVICE_PACKAGE_TYPE_CHARGE = 2

ORDER_STATUS_MAP = {
    11: "未支付",
    12: "已支付",
}

PAYMENT_TYPE_MAP = {
    3: "免费",
    1: "微信",
    2: "支付宝"
}

TASK_STATUS_INIT = 1
TASK_STATUS_START = 2
TASK_STATUS_FINISH = 3
TASK_STATUS_FAIL = 4

TASK_STATUS_DICT = {
    TASK_STATUS_INIT: "初始化",
    TASK_STATUS_START: "已启动",
    TASK_STATUS_FINISH: "已完成",
    TASK_STATUS_FAIL: "失败"
}

SERVICE_TYPE_BAIDU_PC_TOP50 = 10000

SERVICE_TYPE_DICT = {
    SERVICE_TYPE_BAIDU_PC_TOP50: "百度-PC-前50网站信息"
}
